#
# Overcommit Config
# Based on https://gist.github.com/alexcu/6e05d64d04b32bb42b4d
#
CommitMsg:
  ALL:
    on_warn: fail
  EmptyMessage:
    enabled: true
  MessageFormat:
    enabled: true
    pattern: '((NEW|FIX|ENHANCE|LOOKS|SPEED|QUALITY|DOC|CONFIG|TEST): [A-Z].+)|(Merge .+)'
    expected_pattern_message: '<NEW|FIX|ENHANCE|LOOKS|SPEED|QUALITY|DOC|CONFIG|TEST>: <Message Subject>'
    sample_message: 'CONFIG: Add overcommit to project'
  TraillingPeriod:
    enabled: true
  TextWidth:
    enabled: true
PreCommit:
  ALL:
    exclude: &default_excludes
        - 'Figures/**/*'
  AuthorEmail:
    enabled: true
    on_warn: fail
  AuthorName:
    enabled: true
    on_warn: fail
  HardTabs:
    enabled: true
  TrailingWhitespace:
    enabled: true
